source 'https://github.com/Better-me3/XMGFMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'XMGFMMain_Example' do
  pod 'XMGFMMain', :path => '../'

  target 'XMGFMMain_Tests' do
    inherit! :search_paths

    
  end
end
